# Generated by Django 5.1.1 on 2024-09-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bloco', models.IntegerField()),
                ('cultura', models.TextField(max_length=255)),
                ('ph', models.TextField(max_length=255)),
                ('umidade', models.TextField(max_length=255)),
                ('textura', models.TextField(max_length=255)),
            ],
        ),
    ]
