# Generated by Django 5.1.1 on 2024-09-16 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_fazenda', '0003_plantio_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados',
            old_name='cultura',
            new_name='plantio',
        ),
    ]
