# Generated by Django 5.1.1 on 2024-09-16 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_fazenda', '0004_rename_cultura_dados_plantio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plantio',
            new_name='Cultivo',
        ),
        migrations.RenameField(
            model_name='dados',
            old_name='plantio',
            new_name='cultivo',
        ),
    ]
