# Generated by Django 5.1.1 on 2024-10-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fazenda', '0005_rename_plantio_cultivo_rename_plantio_dados_cultivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='texto_recomendacao',
            field=models.TextField(max_length=1200, null=True),
        ),
    ]
