# Generated by Django 5.1.1 on 2024-10-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fazenda', '0006_alter_cultivo_texto_recomendacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
